repos:
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.1
    hooks:
      - id: nbqa-ruff
        args: ["--fix"]
      - id: nbqa-ruff
        alias: nbqa-ruff-format
        name: nbqa-ruff-format
        args: ["format"] 